### ISSUE TITLE
UI composition

### ISSUE THREAD

**Issue by ycs1m1yk** [euphony-io/listen-my-order#2]
Make UI composition here!!

**Comment by YoungSeokHong** [comment]
# UI draft

This is a UI draft based on our meeting
I think we need to use different color (no blue) cause it's for food. Please give me recommendation!
And I want your feedback.

<br/>

![image](https://user-images.githubusercontent.com/80624082/130068485-6bc1b9e9-8891-4cd7-b21a-811e3891c359.png)

**Comment by ycs1m1yk** [comment]
Is this just a draft?! Coooool!! 👍 👍 
By the way, how about color #0be881? It is ***MINTY GREEN*** color.

![image](https://user-images.githubusercontent.com/27720475/130076721-c12a4297-373b-4b61-ab15-bc1a67ed77ed.png)

I found the color here: [flatuicolors.com](https://flatuicolors.com/)

**Comment by hoho00** [comment]
Nice Color I think. But We need to choice secondary color too.

**Comment by HACore** [comment]
It's a really great draft!!
And when it comes to color, since our app is about food, I think the colors that stimulates appetite is good.
These include red, orange, and yellow.

How about these colors?

![image](https://user-images.githubusercontent.com/58473522/130250749-80bc4007-dada-4268-b45d-33e802081d09.png)
#FA983A / rgba(250, 152, 58,1.0)

![image](https://user-images.githubusercontent.com/58473522/130251069-cee98f3e-6f7f-4a06-9c7c-14d48977968a.png)
#F6B93B / rgba(246, 185, 59,1.0)

I referred to this site[(flatuicolors.com)](https://flatuicolors.com/palette/fr) too.

**Comment by YoungSeokHong** [comment]
I just made an "owner page", my part, UI. I want to add an animation button instead of ```Export Menu``` button and make menu retractable.
Later, I'll make an new issue when I have any problem or get to know any important thing during embodying it:)
![image](https://user-images.githubusercontent.com/80624082/130423148-3b1f2b4f-be49-4566-b3b2-bf64f0cdfe02.png)
